"use strict";
module.exports = {
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    NEW_REFRESH_TOKEN: 'NEW_REFRESH_TOKEN',
    NEW_REFRESH_SUCCESS: 'NEW_REFRESH_SUCCESS',
    NEW_REFRESH_FAILURE: 'NEW_REFRESH_FAILURE',
};
//# sourceMappingURL=actionTypes.js.map